Repository andela/ah-rambo-frontend, pull requests merged in 2019-09, with the labels that each got.

#12 Exclude .spec and .test Files in codeClimate
  .codeclimate.yml
Labels: pr:ready

#13 Fix Duplicate File And Eslint File Errors
  .env.development.sample
  .env.production.sample
  .eslintignore
  .eslintrc
  .github/PULL_REQUEST_TEMPLATE.md
  jest.config.js
  jestConfig/__mocks__/fileTransformer.js
  jestConfig/setupTests.js
  nightwatch.conf.js
  sample/sum.sample.js
  sample/sum.sample.test.js
  src/components/Home/Home.scss
  src/components/Home/Home.spec.js
  src/components/Login/login.spec.js
  src/index.js
  src/index.jsx
  src/reducers/index.js
  src/store/index.js
  src/styles/index.scss
Labels: bug, pr:ready

#15 Create Reusable Header Component
  .eslintrc
  assets/icons8-search-96.png
  assets/search-magnifier-interface-symbol.png
  package-lock.json
  package.json
  src/actionTypes/index.js
  src/actions/user/getUserProfile.js
  src/components/App.jsx
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
  src/components/Button/Button.spec.js
  src/components/Form/Form.jsx
  src/components/Form/Form.scss
  src/components/Form/Form.spec.js
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/Header/Header.spec.js
  src/components/Input/Input.jsx
  src/components/Input/Input.scss
  src/components/Input/Input.spec.js
  src/components/SearchForm/SearchForm.jsx
  src/components/SearchForm/SearchForm.scss
  src/components/SearchForm/SearchForm.spec.js
  src/components/TopNav/TopNav.jsx
  src/components/TopNav/TopNav.scss
  src/components/TopNav/TopNav.spec.js
  src/components/index.js
  src/reducers/index.js
  src/reducers/user/index.js
  src/reducers/user/user.spec.js
  src/store/index.js
  src/styles/index.scss
Labels: pr:ready, type:feature

#14 Add Footer component
  assets/icons/facebook.png
  assets/icons/google.png
  assets/icons/index.js
  assets/icons/mail.png
  assets/icons/twitter.png
  src/components/App.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/components/Footer/Footer.spec.js
  src/components/Home/Home.js
  src/helpers/helpers.spec.js
  src/helpers/index.js
  src/styles/index.scss
Labels: pr:review, type:feature

#16 167190491 User Login
  package-lock.json
  package.json
  src/actionTypes/index.js
  src/actions/user/login.js
  src/actions/user/login.spec.js
  src/components/Footer/Footer.scss
  src/components/Login/login.js
  src/components/Login/login.jsx
  src/components/Login/login.scss
  src/components/Login/login.spec.js
  src/components/Router.js
  src/components/common/Button/Button.jsx
  src/components/common/Button/Button.scss
  src/components/common/Button/Button.spec.js
  src/components/common/Form/Form.jsx
  src/components/common/Form/Form.scss
  src/components/common/Form/Form.spec.js
  src/components/common/Input/Input.jsx
  src/components/common/Input/Input.scss
  src/components/common/Input/Input.spec.js
  src/components/common/index.js
  src/components/index.js
  src/reducers/index.js
  src/reducers/user/login.js
  src/reducers/user/user.spec.js
  src/reducers/user/userProfile.js
  src/reducers/validate.test.js
  src/styles/index.scss
  src/styles/variables.scss
Labels: pr:review, type:feature

#21 #167190489 Implement User Signup
  assets/icons/doubleTick.png
  assets/icons/index.js
  assets/icons/searchIcon.png
  assets/icons8-search-96.png
  package-lock.json
  package.json
  src/actionTypes/index.js
  src/actions/user/getUserProfile.js
  src/actions/user/signupAction.js
  src/actions/user/signupAction.spec.js
  src/actions/validate.js
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/Header/Header.spec.js
  src/components/Router.js
  src/components/SearchForm/SearchForm.jsx
  src/components/Signup/Signup.jsx
  src/components/Signup/Signup.scss
  src/components/Signup/Signup.spec.js
  src/components/TopNav/TopNav.jsx
  src/components/TopNav/TopNav.scss
  src/components/common/Form/Form.jsx
  src/components/common/Input/Input.spec.js
  src/components/index.js
  src/helpers/index.js
  src/helpers/mockData.js
  src/helpers/validationHelper.js
  src/reducers/index.js
  src/reducers/user/signupReducer.js
  src/reducers/user/signupReducer.spec.js
  src/reducers/user/user.spec.js
  src/reducers/user/userProfile.js
  src/reducers/validate.js
  src/schemas/signup.js
  webpackConfig/webpack.common.js
Labels: pr:ready, type:feature
