Repository andela/ah-rambo-frontend, pull requests merged in 2019-08, with the labels that each got.

#5 #167190483 Setup End To End Test
  .gitignore
  e2e-tests/index.js
  nightwatch.conf.js
  package-lock.json
  package.json
Labels: pr:ready, type:chore

#3 #167190485 Implement React Router
  package.json
  src/components/Home.js
  src/components/Notfound.js
  src/components/Router.js
  src/components/index.js
  src/components/login.js
  src/index.js
Labels: pr:ready, type:chore

#4 #167190484 Setup CircleCI
  .circleci/config.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  sample/sum.sample.js
  sample/sum.sample.test.js
Labels: pr:ready, type:chore, type:ci, type:docs

#7 #168111036 Setup Heroku Deployment
  app.json
Labels: pr:review, type:chore

#2 #167190481 Setup Empty React Project
  .babelrc
  .env.development.sample
  .env.production.sample
  .eslintignore
  .eslintrc
  .gitignore
  config/webpack.common.js
  config/webpack.dev.js
  config/webpack.prod.js
  package-lock.json
  package.json
  server.js
  src/components/App.jsx
  src/components/Notfound.js
  src/components/Router.js
  src/components/index.js
  src/index.html
  src/index.js
Labels: pr:ready, type:chore

#8 #167190488 Setup Test Coverage Integrations
  .circleci/config.yml
  README.md
  package-lock.json
Labels: pr:ready, type:chore

#6 #167190487 Setup SASS Processing On The Client
  .babelrc
  .circleci/config.yml
  .eslintrc
  .gitignore
  package-lock.json
  package.json
  src/components/Home.js
  src/components/Home/Home.js
  src/components/Home/Home.scss
  src/components/index.js
  src/components/login.js
  src/index.js
  src/styles/index.scss
  src/styles/variables.scss
  webpackConfig/webpack.common.js
  webpackConfig/webpack.dev.js
  webpackConfig/webpack.prod.js
Labels: pr:ready, type:chore

#9 #168137509 Setup Unit Test
  jest.config.js
  jestConfig/__mocks__/fileTransformer.js
  jestConfig/setupTests.js
  package-lock.json
  package.json
  src/components/Home/Home.spec.js
  src/components/Login/login.js
  src/components/Login/login.spec.js
  src/components/NotFound/Notfound.js
  src/components/NotFound/Notfound.spec.js
  src/components/index.js
Labels: pr:ready, type:chore

#11 #167190482 Setup Redux
  package-lock.json
  package.json
  src/actionTypes/index.js
  src/actions/validate.js
  src/index.jsx
  src/reducers/index.js
  src/reducers/validate.js
  src/reducers/validate.test.js
  src/store/index.js
Labels: pr:ready, type:chore
